add_compile_options("-fcoroutines-ts")
set(CMAKE_C_COMPILER "/Users/exbigboss/clang+llvm-6.0.0-x86_64-apple-darwin/bin/clang")
set(CMAKE_CXX_COMPILER "/Users/exbigboss/clang+llvm-6.0.0-x86_64-apple-darwin/bin/clang++")
set(CMAKE_BUILD_TYPE Debug)
# set(BOOST_ROOT "/Users/exbigboss/boosts/boost_167_darwin_x64")
set(Boost_USE_STATIC_LIBS ON)
# include_directories("/Users/exbigboss/cpp/beast/include")
